# Generated by Django 5.2.12 on 2026-04-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='user',
        ),
    ]
